Laupetin/OpenAssetTools

src/Linker/Linker.cpp
src/ObjLoading/AssetLoading/AssetLoadingManager.cpp

Whenever a zone cannot be loaded by the Linker, the linking should abort to avoid unexpected results.

Abort linking on load error

---

docs/example/ExtendZone/zone_source/ExtendZoneProject.zone
docs/example/IPakZone/build.sh
docs/example/IPakZone/zone_source/IPakZone.zone
docs/example/IPakZone/zone_source/IPakZone_ff.zone
docs/example/IPakZone/zone_source/IPakZone_ipak.zone
src/Linker/Linker.cpp
src/Linker/LinkerArgs.cpp
src/Linker/LinkerArgs.h
src/ZoneCommon/Parsing/ZoneDefinition/Sequence/SequenceZoneDefinitionBuild.cpp
src/ZoneCommon/Parsing/ZoneDefinition/Sequence/SequenceZoneDefinitionBuild.h
src/ZoneCommon/Parsing/ZoneDefinition/ZoneDefinitionParser.cpp
src/ZoneCommon/Zone/Definition/ZoneDefinition.h

This adds the following two extensions for the build process:
* Building specific targets within projects
* Specifying targets to build within zone files
Targets are basically the specific zone file that is loaded within a project.
This allows to split the ipak and fastfile targets and have them both within the same project folder which helps to avoid duplicating files or complicated command line args
Additionally this adds an example project showing how to use the improved build process.

Improve IPak building

---

src/ObjLoading/Game/IW4/Menu/MenuConverterIW4.cpp
src/ObjLoading/Game/IW5/Menu/MenuConverterIW5.cpp
src/ObjLoading/Parsing/Menu/Matcher/MenuExpressionMatchers.cpp
src/ObjLoading/Parsing/Menu/MenuAssetZoneState.cpp
src/ObjLoading/Parsing/Menu/MenuFileParserState.cpp
src/ObjLoading/Parsing/Menu/MenuFileParserState.h
src/ObjLoading/Parsing/Menu/Sequence/FunctionScopeSequences.cpp

* Custom functions were not properly case-insensitive
* Could not use base game functions that were registered with capital letters

Fix custom menu function case sensitivity

---

src/ObjLoading/Game/T6/AssetLoaders/AssetLoaderRawFile.cpp
src/ObjLoading/Game/T6/AssetLoaders/AssetLoaderRawFile.h
src/ObjWriting/Game/T6/AssetDumpers/AssetDumperRawFile.cpp
src/ObjWriting/Game/T6/AssetDumpers/AssetDumperRawFile.h

Add the ability to automatically decompress animtrees when dumping, and compress them when linking for T6.

T6 animtree decompression compression

---

.github/workflows/ci.yaml
src/Parser/Parsing/Impl/DefinesStreamProxy.cpp
src/Parser/Parsing/Impl/DefinesStreamProxy.h
src/Parser/Parsing/ParsingException.h
test/ParserTests/Parsing/Impl/DefinesStreamProxyTests.cpp

Two things are wrong here which both need to get fixed.
```
#define TestMacro(param0, \
param1, \
param2) param0 + param1 - param2
```
```
TestMacro(
1,
2,
3
);
```
```
TestMacro((1,1), [2,2], {3,3});
```

Fix macro expansion and definition over multiple lines

---

src/ObjLoading/Parsing/Menu/Sequence/EventHandlerSetScopeSequences.cpp
test/ObjLoadingTests/Parsing/Menu/Sequence/EventHandlerSetScopeSequencesTests.cpp

Accept setLocalVar scripts without value as default value expression

---

src/ObjLoading/Parsing/Menu/Matcher/MenuMatcherFactory.cpp
src/ObjLoading/Parsing/Menu/Matcher/MenuMatcherFactory.h
src/ObjLoading/Parsing/Menu/Sequence/Generic/GenericStringPropertySequence.cpp
src/ObjLoading/Parsing/Menu/Sequence/Generic/GenericStringPropertySequence.h
src/ObjLoading/Parsing/Menu/Sequence/ItemScopeSequences.cpp
test/ObjLoadingTests/Parsing/Menu/Sequence/ItemScopeSequencesTests.cpp

Previously it was not possible to have static expressions for static values that are put into menu properties in all places.
This PR enables static expressions in a lot more places and also adds tests for places where it was previously already possible.

Allow static expressions on all menu item properties

---

src/Common/Game/T6/CommonT6.h
src/Common/Game/T6/T6_Assets.h
src/ObjWriting/Game/T6/AssetDumpers/AssetDumperSndBank.cpp
src/ObjWriting/Game/T6/AssetDumpers/AssetDumperSndDriverGlobals.cpp
src/ObjWriting/Game/T6/AssetDumpers/AssetDumperSndDriverGlobals.h
src/ObjWriting/Game/T6/ZoneDumperT6.cpp

Finish dumping the SndBank asset's relevant pieces as well as SndDriverGlobals
- Dump SndAlias files to CSV
- Dump SndDuck files to JSON
- Dump SndRadverb files to CSV
- Dump SndDuck list file to CSV
- Dump SndDriverGlobals to CSV
The sound driver globals are necessary to dump the SndAlias flags back into the split out columns as well as the duck group & curve group names. Ideally instead of hardcoding these values we should reference the single global SndDriverGlobals asset but I'm not sure if that's necesarry as it is unlikely anyone will want to modify that asset type

T6 SndBank & SndDriverGlobals Asset Dumping

---

src/ZoneCode.lua
src/ZoneCodeGeneratorLib/Domain/Information/StructureInformation.cpp
src/ZoneCodeGeneratorLib/Domain/Information/StructureInformation.h
src/ZoneCodeGeneratorLib/Generating/CodeGenerator.cpp
src/ZoneCodeGeneratorLib/Generating/Templates/ZoneLoadTemplate.cpp
src/ZoneCodeGeneratorLib/Generating/Templates/ZoneMarkTemplate.cpp
src/ZoneCodeGeneratorLib/Generating/Templates/ZoneMarkTemplate.h
src/ZoneCodeGeneratorLib/Parsing/Commands/CommandsFileReader.cpp
src/ZoneCodeGeneratorLib/Parsing/PostProcessing/MarkingRequiredPostProcessor.cpp
src/ZoneCodeGeneratorLib/Parsing/PostProcessing/MarkingRequiredPostProcessor.h
src/ZoneLoading/Loading/AssetLoader.cpp
src/ZoneLoading/Loading/AssetLoader.h
src/ZoneLoading/Loading/AssetMarker.cpp
src/ZoneLoading/Loading/AssetMarker.h

Previously, whenever an asset used a substruct via zone pointer instead of loading it itself, all contained scriptstrings were not registered as usage of the asset and all contained assets were not added as a dependency.
This may have lead to odd side effects when loading selected assets from another zone from in-memory.
This could be a potential fix for #65

fix: introduce asset marking to catch all scriptstrings and dependencies

---

premake5.lua
src/Linker/Linker.cpp
src/Linker/LinkerArgs.cpp
src/Linker/LinkerArgs.h
src/RawTemplater/RawTemplater.cpp
src/RawTemplater/RawTemplaterArguments.cpp
src/RawTemplater/RawTemplaterArguments.h
src/Unlinker/Unlinker.cpp
src/Unlinker/UnlinkerArgs.cpp
src/Unlinker/UnlinkerArgs.h
src/ZoneCodeGeneratorLib/ZoneCodeGenerator.cpp
src/ZoneCodeGeneratorLib/ZoneCodeGeneratorArguments.cpp
src/ZoneCodeGeneratorLib/ZoneCodeGeneratorArguments.h
tools/scripts/version.lua

This adds a `--version` command line arg to all executables:
* Linker
* Unlinker
* ZoneCodeGenerator
* RawTemplater
Also the `--help` command line arg does not return exit code `1` anymore now.

feat: add version command line arg

---

src/ObjLoading/Game/T6/AssetLoaders/AssetLoaderWeapon.cpp
src/ObjLoading/Game/T6/AssetLoaders/AssetLoaderWeapon.h

Vanilla weapons interpret an empty hideTags value as nullptr value.
OAT did interpret it as an empty string however.
Some weapons have bones with an empty string as their name.
This made all weapons have these bones hidden even though they are not supposed to be.

fix: weapon hidetags use empty string when they should be using nullptr

---

src/ZoneCommon/Pool/XAssetInfo.cpp

fix: indirect asset references may not be fully lower case

---

src/ObjLoading/Game/T6/AssetLoaders/AssetLoaderSoundBank.cpp

Currently "file" is a required field in the sound aliases. There are scenarios where this should be blank. This allows adding those aliases and ignored them when building the sound bank files

fix: T6 - allow sound aliases without explicit files

---

src/ObjLoading/ObjContainer/SoundBank/SoundBankWriter.cpp

Some sound aliases use the same asset file. We do not need to add the same file to a bank multiple times

do not add duplicate sounds to the sab files

---

src/ObjLoading/AssetLoading/AssetLoadingManager.cpp
src/ZoneCodeGeneratorLib/Generating/Templates/ZoneWriteTemplate.cpp
src/ZoneCommon/Game/IW3/GameAssetPoolIW3.cpp
src/ZoneCommon/Game/IW3/GameAssetPoolIW3.h
src/ZoneCommon/Game/IW4/GameAssetPoolIW4.cpp
src/ZoneCommon/Game/IW4/GameAssetPoolIW4.h
src/ZoneCommon/Game/IW5/GameAssetPoolIW5.cpp
src/ZoneCommon/Game/IW5/GameAssetPoolIW5.h
src/ZoneCommon/Game/T5/GameAssetPoolT5.cpp
src/ZoneCommon/Game/T5/GameAssetPoolT5.h
src/ZoneCommon/Game/T6/GameAssetPoolT6.cpp
src/ZoneCommon/Game/T6/GameAssetPoolT6.h
src/ZoneCommon/Pool/ZoneAssetPools.cpp
src/ZoneCommon/Pool/ZoneAssetPools.h
src/ZoneLoading/Loading/AssetLoader.cpp
src/ZoneLoading/Loading/AssetLoader.h
src/ZoneLoading/Loading/AssetMarker.cpp
src/ZoneLoading/Loading/AssetMarker.h

When trying to write an asset with the name `xyz` while the zone only contains an asset called `,xyz`, it will crash.
This can happen with indirect asset references for example.

fix: crash on trying to link asset with only a referenced asset loaded

---

src/ZoneCode/Game/IW5/XAssets/clipMap_t.txt
src/ZoneCodeGeneratorLib/Domain/Information/MemberInformation.h
src/ZoneCodeGeneratorLib/Generating/RenderingContext.cpp
src/ZoneCodeGeneratorLib/Generating/RenderingContext.h
src/ZoneCodeGeneratorLib/Generating/Templates/ZoneLoadTemplate.cpp
src/ZoneCodeGeneratorLib/Parsing/Commands/Sequence/SequenceAction.cpp
src/ZoneLoading/Game/IW5/XAssets/clipmap_t/clipmap_t_actions.cpp
src/ZoneLoading/Game/IW5/XAssets/clipmap_t/clipmap_t_actions.h
test/ZoneCodeGeneratorLibTests/Parsing/Commands/Sequence/SequenceActionTests.cpp

The IW5 `pInfo` member is not reallocated upon loading even though it is part of the temp block.
When trying to write this data again when reusing it from a loaded zone, it will try to write garbage data and therefore crash.

fix: not reallocating IW5 clipMap pInfo from temp block

---

src/ObjWriting/Game/IW4/AssetDumpers/AssetDumperStringTable.cpp
src/ObjWriting/Game/IW5/AssetDumpers/AssetDumperStringTable.cpp
src/ObjWriting/Game/T5/AssetDumpers/AssetDumperStringTable.cpp
src/ObjWriting/Game/T6/AssetDumpers/AssetDumperStringTable.cpp

Hello,
when dumping zones generated by other tools, there is a small possibility that the string fields of the string table are empty.
This causes OAT to crash because it will try to build an std::string from a NULL char*
I have tested this PR post and pre fix with the following fastfile
[plutonium_code_post_gfx_mp.zip](https://github.com/Laupetin/OpenAssetTools/files/15052498/plutonium_code_post_gfx_mp.zip)

fix: check for NULL string in stringtable check before dumping

---

src/ObjLoading/Game/IW4/AssetLoaders/AssetLoaderRawFile.cpp
src/ObjLoading/Game/IW4/AssetLoaders/AssetLoaderRawFile.h
src/ObjLoading/Game/IW5/AssetLoaders/AssetLoaderRawFile.cpp
src/ObjLoading/Game/T5/AssetLoaders/AssetLoaderRawFile.cpp
src/ObjLoading/Game/T6/AssetLoaders/AssetLoaderRawFile.cpp

Hello, this Pull Request adds code to the IW4 rawfile obj loader code that will compress the file just like it does on IW5.
The reason is that the game seems to have compressed rawfiles in itself. Additionally, other tools like ZoneBuilder and ZoneTool seem to also compress their rawfile for the IW4 engine.

maint(iw4): compress rawfiles just like on IW5 (fix zlib mem leak IW4, T5, IW5)

---

src/ObjLoading/AssetLoading/AssetLoadingManager.cpp
src/ObjLoading/AssetLoading/AssetLoadingManager.h
src/ObjLoading/AssetLoading/IAssetLoadingManager.h
src/ObjLoading/Game/IW4/AssetLoaders/AssetLoaderWeapon.cpp
src/ObjLoading/Game/IW5/AssetLoaders/AssetLoaderWeapon.cpp
src/ObjLoading/Game/T6/AssetLoaders/AssetLoaderWeapon.cpp
src/ObjLoading/Game/T6/AssetLoaders/AssetLoaderWeaponAttachmentUnique.cpp
test/ObjLoadingTests/Mock/MockAssetLoadingManager.cpp
test/ObjLoadingTests/Mock/MockAssetLoadingManager.h

* All asset names are converted to lowercase
* All `\` characters in asset names are replaced with `/`
Closes #82
Closes #173

feat: normalize asset names

---

src/ObjLoading/AssetLoading/AssetLoadingManager.cpp
src/ObjLoading/AssetLoading/AssetLoadingManager.h
src/ZoneCommon/Pool/AssetPool.h
src/ZoneCommon/Pool/AssetPoolDynamic.h
src/ZoneCommon/Pool/AssetPoolStatic.h
src/ZoneCommon/Pool/GlobalAssetPool.h
src/ZoneCommon/Pool/XAssetInfo.cpp
src/ZoneCommon/Pool/XAssetInfo.h

This normalizes all asset names before adding them to the asset lookup, enabling case insensitive search for assets.

feat: make asset lookup work case insensitively entirely

---

src/ObjLoading/AssetLoading/AssetLoadingManager.cpp

Asset names were normalized when loading because i assumed all asset names were normalized anyway.
Leaderboards are an obvious counter example to this since their names are all uppercase.
Since the main thing that has be correct is that asset lookup is being done case insensitively, the inteded effect of the original change was to make this happen, but it is now covered already by normalizing asset names for lookup.
So now this reverts back normalizing asset names upon load so you can have leaderboards have uppercase names again for example, as they are in vanilla fastfiles.

fix: do not normalize asset names when loading assets

---

src/Linker/Game/T6/ZoneCreatorT6.cpp
src/Linker/Linker.cpp

Before when specifying `t6` as a game name, linker just exited without an error message and without building a zone.
Now game names are case insensitive and an error message is logged when a game name is unrecognized.
Fixes: #141

fix: make game name case insensitive

---

src/Linker/Linker.cpp
src/Unlinker/Unlinker.cpp

Currently Unlinker cannot unlink a file when specified in the following way:
`./Unlinker file.ff`
It had to be specified in the following way:
`./Unlinker ./file.ff`
with a `./` prefix.
This fixes that unintended behaviour to make the prefix no longer required.

fix: referencing files in cwd without dot slash

---

src/ObjCommon/XModel/Gltf/JsonGltf.h
src/ObjLoading/XModel/Gltf/GltfLoader.cpp

Some tools seem to write node transformations as the matrix notation.
Bones will now support this.

feat: support gltf bone rotation as matrix notation

---

src/ObjLoading/Game/T6/XModel/JsonXModelLoader.cpp

XModels without bones do not work, there has to be at least one bone that every vertex is part of.

fix: auto generate armature when imported gltf has none

---

src/ObjWriting/Game/T6/AssetDumpers/AssetDumperXModel.cpp
src/ObjWriting/XModel/Gltf/GltfWriter.cpp

When a model just has a single bone that has a weight of 100% for all vertices, the armature is omitted when dumping the model.
When loading the model again, this armature will be generated again anyway since #254

feat: omit default armature when dumping xmodels

---

src/Linker/LinkerArgs.cpp
src/Linker/LinkerArgs.h

Before when using Linker from a different working directory, it was not able to locate it shipped raw files.
Now it resolves that path relative to the binary.

feat: load raw game folder relative to binary

---

src/Linker/LinkerArgs.cpp
src/Linker/LinkerArgs.h

* Add default of `zone_raw/?project?` as source search path
* Add command `--add-asset-search-path` to add asset search paths without overriding all asset search paths
* Add command `--add-source-search-path` to add source search paths without overriding all source search paths

feat: better linker search paths

---

src/Linker/Linker.cpp

Tackles in part #177 
Tracking time spent while linking is cool but I could do that some other time and then I can close that issue.

feat(Linker): add verbose loggin when writing of zones begins

---

src/ZoneWriting/ZoneWriting.cpp

Closes #177 
This completes the features I requested. This is greatly inspired by how ZoneTool tracks the msec passed when linking a Zone.

feat: track time spent linking zone

---

src/Common/Game/T6/T6_Assets.h
src/ObjCommon/Game/T6/SoundConstantsT6.h
src/ObjLoading/Game/T6/AssetLoaders/AssetLoaderSoundBank.cpp
src/ObjLoading/ObjContainer/SoundBank/SoundBankWriter.cpp
src/ObjWriting/Game/T6/AssetDumpers/AssetDumperSndBank.cpp

Closes #138 if `raw\` doesn't need to be removed.
Dumps sound extensions and requires sound extensions for loading.
Fixes 8 bit values dumping as signed instead of unsigned.
Fixes `SOUND_RANDOMIZE_TYPES` enum dumping default value of "volume" instead of "".

Various soundbank fixes

---

src/ObjLoading/ObjContainer/SoundBank/SoundBankWriter.cpp

The default sound filenames in T6 have multiple "." in them, so using `replace_extension` was cutting off the last part of the filename.
Example:
```
sound/wpn/pistol/fnp45/plr/shot/wpn_fnp45_fire_plr.LN65.pc.snd
```
was becoming:
```
sound/wpn/pistol/fnp45/plr/shot/wpn_fnp45_fire_plr.LN65.pc.wav
```
where it should be:
```
sound/wpn/pistol/fnp45/plr/shot/wpn_fnp45_fire_plr.LN65.pc.snd.wav
```

Fix guess sound filename function

---

src/Common/Game/T6/CommonT6.h
src/ObjLoading/Game/T6/AssetLoaders/AssetLoaderSoundBank.cpp
src/ObjWriting/Game/T6/AssetDumpers/AssetDumperSndBank.cpp

I became a scholar of music theory to figure out what these values were representing.
BO1 and BO3 sound aliases have volume values ranging from 0 to 100, and pitch values ranging from -2400 to 1200.
The amp ratio value is due to 100 decibels being equal to 100,000 amplitude, but the value is stored in 16 bits.
[Decibel converter](https://www.silisoftware.com/tools/db.php)
[Cents converter](https://sengpielaudio.com/calculator-centsratio.htm)

Dump and load correct volume and pitch values for T6 sound aliases

---

src/Common/Game/T6/CommonT6.cpp
src/Common/Game/T6/CommonT6.h
src/Common/Game/T6/T6_Assets.h
src/ObjLoading/Game/T6/AssetLoaders/AssetLoaderSoundBank.cpp
src/ObjWriting/Game/T6/AssetDumpers/AssetDumperSndBank.cpp

Reorganized the sound alias columns to be more similar to T7.
Added rounding formula for float values to dump the least possible precision that still gives the correct value after conversion.
Fixed PitchMin, PitchMax, and RandomizeType being dumped incorrectly.

Improve sound bank dumping

---

src/ObjLoading/Game/T6/AssetLoaders/AssetLoaderSoundBank.cpp
src/ObjLoading/ObjContainer/SoundBank/SoundBankWriter.cpp

Sound aliases should always be defined using their extension

fix: stop removing extensions of soundaliases

---

src/ZoneCommon/Zone/Definition/ZoneDefinition.h

Stuff like ipak_read can be specified multiple times, so it needs to be a multimap

fix: use multimap again for zone definition properties

---

src/Linker/Linker.cpp
src/ZoneCommon/Parsing/ZoneDefinition/ZoneDefinitionParser.cpp
src/ZoneCommon/Parsing/ZoneDefinition/ZoneDefinitionParser.h
src/ZoneCommon/Parsing/ZoneDefinition/ZoneDefinitionParserState.cpp
src/ZoneCommon/Parsing/ZoneDefinition/ZoneDefinitionParserState.h
src/ZoneCommon/Zone/Definition/ZoneDefinitionStream.cpp
src/ZoneCommon/Zone/Definition/ZoneDefinitionStream.h
test/ZoneCommonTests/Zone/Definition/ZoneDefinitionStreamTests.cpp

Refactor of ZoneDefinition reading did break default zone definition names.
fixes: #302

fix: make name of zone definition the target name by default

---

src/ObjWriting/Dumping/AssetDumpingContext.cpp
src/ObjWriting/Game/IW4/AssetDumpers/AssetDumperRawFile.cpp
src/ObjWriting/Game/IW5/AssetDumpers/AssetDumperRawFile.cpp

Also while I was looking at dumper code for iw4 and iw5 for unrelated reason I unified the error message as they were different

Recover from filesystem exception when dumping

---

src/ZoneCommon/Zone/XChunk/AbstractSalsa20Processor.cpp
src/ZoneLoading/Loading/Exception/InvalidFileNameException.cpp
src/ZoneLoading/Loading/Exception/InvalidFileNameException.h
src/ZoneLoading/Loading/Steps/StepVerifyFileName.cpp
src/ZoneLoading/Loading/Steps/StepVerifyFileName.h

Loading fastfiles with long names that get cut off internally is currently broken, as can be seen for `weapons!concussion_grenade_80s_sp.ff` for example.

fix: long fastfile names

---

src/ObjWriting/XModel/Gltf/GltfWriter.cpp
src/ObjWriting/XModel/XModelDumper.cpp.template

Primitives are not able to be seen in Blender, meshes can.
That makes it easier to separate different parts of an xmodel.

feat: separate objects into gltf meshes instead of primitives

---

src/Crypto/Impl/Base64.cpp
src/Crypto/Impl/Base64.h
src/ObjLoading/XModel/Gltf/Internal/GltfBuffer.cpp

The output length of the base64 is calculated incorrectly

fix: loading of base64 data from gltf files

---

src/Common/Game/T6/T6_Assets.h

CI currently errors on:
```
D:\a\OpenAssetTools\OpenAssetTools\build\src\ZoneCode\Game\T6\XAssets\gfxworld\gfxworld_struct_test.cpp(623,9): error C2872: '__m128': ambiguous symbol [D:\a\OpenAssetTools\OpenAssetTools\build\test\ZoneCommonTests\ZoneCommonTests.vcxproj]
```

fix: compilation on msvc

---

src/ObjLoading/Game/T6/ObjLoaderT6.cpp
src/ObjWriting/Game/T6/ObjWriterT6.cpp
src/ZoneCommon/Game/T6/GameAssetPoolT6.cpp

BO2's ASSET_TYPE_CLIPMAP is unused, and instead uses ASSET_TYPE_CLIPMAP_PVS both in the game code and fastfiles, so I've updated the asset code to only use ASSET_TYPE_CLIPMAP_PVS. This doesn't effect the .zone files and is just a backend change.

Update T6 asset loading code to use ASSET_TYPE_CLIPMAP_PVS.

---

src/ObjLoading/Game/IW3/ObjLoaderIW3.cpp
src/ObjLoading/Game/IW4/ObjLoaderIW4.cpp
src/ObjLoading/Game/T5/ObjLoaderT5.cpp
src/ObjWriting/Game/IW3/ObjWriterIW3.cpp
src/ObjWriting/Game/IW4/ObjWriterIW4.cpp
src/ObjWriting/Game/T5/ObjWriterT5.cpp
src/ZoneCommon/Game/IW3/GameAssetPoolIW3.cpp
src/ZoneCommon/Game/IW4/GameAssetPoolIW4.cpp
src/ZoneCommon/Game/T5/GameAssetPoolT5.cpp

Adjust asset names of remaining games that appear to have the same problem as T6 (as fixed in #391)

fix: set clipmap asset name of non-pvs clipmap to clipmap_unused in IW3,IW4,T5

---

src/Linker/LinkerPaths.cpp
src/ObjWriting/XModel/XModelDumper.cpp.template

It already worked on Windows due to not considering files different with different capitalization.
Linux does however so the linker game path variable and xmodel file extensions did not match the files they meant to.
Now all these places use lower case file names and folder names.

fix: linux folder file capitalization

---

src/ObjLoading/XModel/Gltf/GltfLoader.cpp
src/ObjLoading/XModel/LoaderXModel.cpp.template

Vertex sorting was messed up and caused some vertex explosions in some cases where actual reordering takes place.

fix: bad xmodel loading

---

src/ObjImage/Image/IwiWriter13.cpp
src/ObjImage/Image/IwiWriter27.cpp
src/ObjImage/Image/IwiWriter6.cpp
src/ObjImage/Image/IwiWriter8.cpp

When dumping cube images as an IWI, they are incorrectly saved with a 2D image header instead which makes it impossible to load them again (e.g. bo2 reflection probes). 
As the class TextureCube extends Texture2D, a dynamic_cast to Texture2D will work on both TextureCube and Texture2D. The IWI saving code checks a dynamic_cast to Texture2D first, so if a TextureCube class is given it will match Texture2D and be dumped as a Texture2D. This pull request fixes the issue by checking Texture2D after TextureCube so cube images are correctly dumped as a TextureCube.
This issue might be present in other IWI versions but I haven't checked.

Fix BO2 IWI files saving cube textures incorrectly.

---

src/Common/Game/IW3/IW3_Assets.h
src/Common/Game/T5/T5_Assets.h
src/ZoneLoading/Game/IW3/ZoneLoaderFactoryIW3.cpp
src/ZoneLoading/Game/IW5/ZoneLoaderFactoryIW5.cpp
src/ZoneLoading/Game/T5/ZoneLoaderFactoryT5.cpp
src/ZoneLoading/Game/T6/ZoneLoaderFactoryT6.cpp

Made two mistakes when fixing XQuat struct with filling and forgot to apply fix from iw4 to other games as well in regards to passing zone to content loader
fixes: #454

fix: x86 ff loading broken due to x64 updates

---

src/Common/Game/T5/T5_Assets.h
src/Common/Game/T6/T6_Assets.h
src/ObjCommon/XModel/JsonXModel.h.template
src/ObjLoading/XModel/Gltf/GltfLoader.cpp
src/ObjLoading/XModel/LoaderXModel.cpp.template
src/ObjWriting/XModel/XModelDumper.cpp.template

* Load animated models
* Animated models are any models where the max bone count per vertex in the model is more than 1
* This means that no vertex is affected by more than 1 bone, it is rigid, otherwise animated.
* Viewhands models need special treatment, there a new `type` property in xmodel jsons specifies the type
* Currently only `viewhands` adds special viewhands treatment to the model, other values are not made use of

feat: xmodel load non rigid
